name: Materials preview

on:
  pull_request:
    paths:
      - '*/agenda.md'
      - '*/minutes.md'
      - '*/slides-*'

permissions:
  contents: read
  pull-requests: write

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ekinnear/wg-materials-template@main
        with:
          token: ${{ github.token }}
          pr: ${{ github.event.pull_request.number }}
